#include<bits/stdc++.h>
using namespace std;

// LeetCode - 2

struct ListNode { // This generated by me to remove error in code
    int val;
    ListNode *next;
    ListNode() : val(0), next(nullptr) {}
    ListNode(int x) : val(x), next(nullptr) {}
    ListNode(int x, ListNode *next) : val(x), next(next) {}
};

class Solution {
public:
    ListNode* addTwoNumbers(ListNode* l1, ListNode* l2) {
        ListNode* dummy = new ListNode(-1);
        ListNode* temp = dummy;
        int carry = 0;
        while(l1 || l2){
            int val = carry;
            if(l1){
                val+=l1->val;
                 l1 = l1->next;
            }
            if(l2){
                val+=l2->val;
                l2 = l2->next;
            }
            carry = val/10;
            temp->next = new ListNode(val%10);
            temp = temp->next;
        }
        if(carry)
            temp->next = new ListNode(carry);
        return dummy->next;
    }
};