#include<bits/stdc++.h>
using namespace std;

// GFG - Count Number of SubTrees having given Sum

struct Node{ // // This generated by me to remove error in code
    int data;
    struct Node* left;
    struct Node* right;
};
int postOrder(Node* root, int X, int &ans){
    if(!root)
        return 0;
    int left = postOrder(root->left,X,ans);
    int right = postOrder(root->right,X,ans);
    int x = left+right+root->data;
    if(x==X){
        ans++;
    }
    return x;
}
int countSubtreesWithSumX(Node* root, int X)
{
    int ans = 0;
	postOrder(root,X, ans);
	return ans;
}