#include<bits/stdc++.h>
using namespace std;

// LeetCode - 894


struct TreeNode { // This generated by me to remove error in code
     int val;
     TreeNode *left;
     TreeNode *right;
     TreeNode() : val(0), left(nullptr), right(nullptr) {}
     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
 };


class Solution {
    vector<TreeNode*> f(int n){
        if(n == 1)
            return {new TreeNode(0)};
        vector<TreeNode*> ans;
        for(int i = 1; i<n; i+=2){
            auto left = f(i);
            auto right= f(n-i-1);
            for(auto l : left){
                for(auto r: right){
                    TreeNode* newNode = new TreeNode(0);
                    newNode->left = l;
                    newNode->right = r;
                    ans.push_back(newNode);
                }
            }
        }
        return ans;
    }
public:
    vector<TreeNode*> allPossibleFBT(int n) {
        if(!(n&1))
            return {};
        return f(n);
    }
};