#include<bits/stdc++.h>
using namespace std;

// LeetCode - 449 

struct TreeNode { // This generated by me to remove error in code
    int val;
    TreeNode *left;
    TreeNode *right;
    TreeNode(int x) : val(x), left(NULL), right(NULL) {}
};

class Codec {
    void inordered(TreeNode* root, string &ans){
        if(!root){
            return;
        }
        ans+=to_string(root->val)+"-";
        inordered(root->left, ans);
        inordered(root->right, ans);
    }
    TreeNode* inordered(TreeNode* root, int val){
        if(!root){
            return new TreeNode(val);
        }
        if(val<root->val)
            root->left = inordered(root->left, val);
        else
            root->right = inordered(root->right, val);
        return root;
    }
public:
    string serialize(TreeNode* root) {
        string ans = "";
        inordered(root,ans);
        ans.pop_back();
        return ans;
    }
    TreeNode* deserialize(string &data) {
        int n = data.size();
        if(n == 0)
            return NULL;
        vector<int> arr;
        for(int i = 0; i<n; i++){
            int val = 0;
            while(i<n && isdigit(data[i])){
                val*=10;
                val+=(int)(data[i]-'0');
                i++;
            }
            arr.push_back(val);
        }
        TreeNode* root = NULL;
        for(int i = 0; i<arr.size(); i++){
           root = inordered(root, arr[i]);
        }
        return root;
    }
};
