#include <bits/stdc++.h>
using namespace std;

// LeetCode - 206

struct ListNode{ // This generated by me to remove error in code
    int val;
    ListNode *next;
    ListNode(int data){
        this->val = data;
        next = NULL;
    }
};

class Solution{
public:
    ListNode *reverseList(ListNode *head){
        if (!head || !head->next)
            return head;
        ListNode *prev = reverseList(head->next);
        head->next->next = head;
        head->next = NULL;
        return prev;
    }

    // Another method using Three Pointer
    ListNode *reverseLink(ListNode *head){
        if (!head)
            return head;
        ListNode *prev = NULL;
        ListNode *cur = head;
        ListNode *next = NULL;
        while (cur)
        {
            next = cur->next;
            cur->next = prev;
            prev = cur;
            cur = next;
        }
        return prev;
    }
};
