#include<bits/stdc++.h>
using namespace std;

// LeetCode - 234


struct ListNode{ // This generated by me to remove error in code
    int val;
    ListNode *next;
    ListNode(int data){
        this->val = data;
        next = NULL;
    }
};


class Solution {
    ListNode* first;
    bool isPalindromeOrNot(ListNode* head){
        if(!head)
            return true;
        bool is = isPalindromeOrNot(head->next);
        if(!is)
            return is;
        is = first->val == head->val;
        first = first->next;
        return is;
    }
public:
    bool isPalindrome(ListNode* head) {
        first = head;
        return isPalindromeOrNot(head);
    }
};